//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoriesEntities : DbContext
    {
        public StoriesEntities()
            : base("name=StoriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRF_EducationField> PRF_EducationField { get; set; }
        public virtual DbSet<PRF_EducationLevel> PRF_EducationLevel { get; set; }
        public virtual DbSet<PRF_Follow> PRF_Follow { get; set; }
        public virtual DbSet<PRF_Interest> PRF_Interest { get; set; }
        public virtual DbSet<PRF_UserInterest> PRF_UserInterest { get; set; }
        public virtual DbSet<PRF_WorkField> PRF_WorkField { get; set; }
        public virtual DbSet<STR_CommentOfStory> STR_CommentOfStory { get; set; }
        public virtual DbSet<STR_RateOfStory> STR_RateOfStory { get; set; }
        public virtual DbSet<STR_RateSubject> STR_RateSubject { get; set; }
        public virtual DbSet<STR_ReportOfComment> STR_ReportOfComment { get; set; }
        public virtual DbSet<STR_ReportOfStory> STR_ReportOfStory { get; set; }
        public virtual DbSet<STR_ReportSubject> STR_ReportSubject { get; set; }
        public virtual DbSet<STR_Tag> STR_Tag { get; set; }
        public virtual DbSet<STR_TagOfStory> STR_TagOfStory { get; set; }
        public virtual DbSet<STR_Topic> STR_Topic { get; set; }
        public virtual DbSet<STR_UserTopic> STR_UserTopic { get; set; }
        public virtual DbSet<PRF_UserProfile> PRF_UserProfile { get; set; }
        public virtual DbSet<STR_StoryStatus> STR_StoryStatus { get; set; }
        public virtual DbSet<STR_LikeOfStory> STR_LikeOfStory { get; set; }
        public virtual DbSet<STR_Story> STR_Story { get; set; }
        public virtual DbSet<PRF_UserAccount> PRF_UserAccount { get; set; }
    }
}
