//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRF_WorkField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRF_WorkField()
        {
            this.PRF_UserProfile = new HashSet<PRF_UserProfile>();
        }
    
        public int Id { get; set; }
        public string Caption { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRF_UserProfile> PRF_UserProfile { get; set; }
    }
}
