//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRF_UserAccount
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserProfileId { get; set; }
        public string EmailAddress { get; set; }
        public string Token { get; set; }
    
        public virtual PRF_UserProfile PRF_UserProfile { get; set; }
    }
}
