//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRF_UserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRF_UserProfile()
        {
            this.PRF_Follow = new HashSet<PRF_Follow>();
            this.PRF_Follow1 = new HashSet<PRF_Follow>();
            this.PRF_UserInterest = new HashSet<PRF_UserInterest>();
            this.STR_CommentOfStory = new HashSet<STR_CommentOfStory>();
            this.STR_RateOfStory = new HashSet<STR_RateOfStory>();
            this.STR_ReportOfComment = new HashSet<STR_ReportOfComment>();
            this.STR_ReportOfStory = new HashSet<STR_ReportOfStory>();
            this.STR_LikeOfStory = new HashSet<STR_LikeOfStory>();
            this.STR_Story = new HashSet<STR_Story>();
            this.PRF_UserAccount = new HashSet<PRF_UserAccount>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public Nullable<int> EducationFieldId { get; set; }
        public Nullable<int> WorkFieldId { get; set; }
        public string Bio { get; set; }
        public byte[] ProfileImage { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual PRF_EducationField PRF_EducationField { get; set; }
        public virtual PRF_EducationLevel PRF_EducationLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRF_Follow> PRF_Follow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRF_Follow> PRF_Follow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRF_UserInterest> PRF_UserInterest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_CommentOfStory> STR_CommentOfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_RateOfStory> STR_RateOfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_ReportOfComment> STR_ReportOfComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_ReportOfStory> STR_ReportOfStory { get; set; }
        public virtual PRF_WorkField PRF_WorkField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_LikeOfStory> STR_LikeOfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_Story> STR_Story { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRF_UserAccount> PRF_UserAccount { get; set; }
    }
}
