//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRF_UserInterest
    {
        public System.Guid Id { get; set; }
        public int InterestId { get; set; }
        public System.Guid UserProfileId { get; set; }
    
        public virtual PRF_Interest PRF_Interest { get; set; }
        public virtual PRF_UserProfile PRF_UserProfile { get; set; }
    }
}
