//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR_RateOfStory
    {
        public System.Guid Id { get; set; }
        public System.Guid StoryId { get; set; }
        public System.Guid UserProfileId { get; set; }
        public int RateSubjectId { get; set; }
        public short Rate { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual STR_RateSubject STR_RateSubject { get; set; }
        public virtual PRF_UserProfile PRF_UserProfile { get; set; }
        public virtual STR_Story STR_Story { get; set; }
    }
}
