//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR_TagOfStory
    {
        public System.Guid Id { get; set; }
        public System.Guid StoryId { get; set; }
        public System.Guid TagId { get; set; }
    
        public virtual STR_Tag STR_Tag { get; set; }
        public virtual STR_Story STR_Story { get; set; }
    }
}
