//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR_Story
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STR_Story()
        {
            this.STR_CommentOfStory = new HashSet<STR_CommentOfStory>();
            this.STR_LikeOfStory = new HashSet<STR_LikeOfStory>();
            this.STR_RateOfStory = new HashSet<STR_RateOfStory>();
            this.STR_ReportOfStory = new HashSet<STR_ReportOfStory>();
            this.STR_TagOfStory = new HashSet<STR_TagOfStory>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserProfileId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int TopicId { get; set; }
        public byte[] StoryImage { get; set; }
        public int StoryStatusId { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual PRF_UserProfile PRF_UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_CommentOfStory> STR_CommentOfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_LikeOfStory> STR_LikeOfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_RateOfStory> STR_RateOfStory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_ReportOfStory> STR_ReportOfStory { get; set; }
        public virtual STR_Topic STR_Topic { get; set; }
        public virtual STR_StoryStatus STR_StoryStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_TagOfStory> STR_TagOfStory { get; set; }
    }
}
