//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR_ReportOfComment
    {
        public System.Guid Id { get; set; }
        public System.Guid UserProfileId { get; set; }
        public System.Guid CommentId { get; set; }
        public int ReportSubjectId { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual STR_CommentOfStory STR_CommentOfStory { get; set; }
        public virtual STR_ReportSubject STR_ReportSubject { get; set; }
        public virtual PRF_UserProfile PRF_UserProfile { get; set; }
    }
}
