//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stories.Dal.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR_CommentOfStory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STR_CommentOfStory()
        {
            this.STR_CommentOfStory1 = new HashSet<STR_CommentOfStory>();
            this.STR_ReportOfComment = new HashSet<STR_ReportOfComment>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid UserProfileId { get; set; }
        public System.Guid StoryId { get; set; }
        public string Comment { get; set; }
        public bool IsReply { get; set; }
        public Nullable<System.Guid> ReplyToId { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_CommentOfStory> STR_CommentOfStory1 { get; set; }
        public virtual STR_CommentOfStory STR_CommentOfStory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR_ReportOfComment> STR_ReportOfComment { get; set; }
        public virtual PRF_UserProfile PRF_UserProfile { get; set; }
        public virtual STR_Story STR_Story { get; set; }
    }
}
